GITHUB & NINCAT: updated options and added 'update'
Now it loads directly from a file instead of using the find command
every single time. This in the long term it will definitely be better
for users.

Fixes #2.

diff --git a/nincat b/nincat
--- a/nincat
+++ b/nincat
@@ -14,7 +14,6 @@
 # 
 # TODO:
 #   ? Support HEX colours (true colours) (maybe?)
-#   + File with list of names to ignore certain arts! Faster than O(n)
 #
 # NOTE:
 #   Keep the current syntax for developing!
@@ -30,7 +29,7 @@
 # recommend you to put in somewhere that you can update to get new arts!
 # Obviously if you call it with an environment variable, as `path_script`, it 
 # will override.
-path_script="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)/ascii_arts"
+path_script="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
 
 # NOTE 2:
 # Print the art in the terminal. It accepts only one argument which will help
@@ -75,7 +74,7 @@ case "$1" in
   # NOTE 3.1:
   # This option will show the secondpath of all ASCII arts files that nincat can
   # find.
-  list | l)
+  list | '-l')
 
     # NOTE 3.1.1:
     # Print all the arts files that it finds with the `find` command, it will
@@ -83,15 +82,22 @@ case "$1" in
     # that we add a `.ignorearts` file to keep updating without overriding the
     # art that we changed or updated. Verify if the file exists and then put
     # it path if it does.
-    find "$path_script" -type f -size +0 | \
-      sed "s*$path_script/**" | \
-      awk '{print $(NF-2), $(NF-1), $NF}'; exit 0
+    cat "$path_script/nincat_list" || {
+
+      echo "nincat: The file list was not found on the root directory.\n" \
+           "nincat will try to create it by itself. If it doesn't work, try" \
+           "running 'nincat update'."
+      exec "$path_script/nincat" 'update'
+      
+    }
+
+    exit 0
 
   ;;
 
   # NOTE 3.2:
   # This will show an ASCII art based on the secondpath that is given.
-  view | v)
+  view | '-v')
   
     # NOTE 3.2.1:
     # If there's an argument (which is the filename secondpath), then choose it 
@@ -99,7 +105,7 @@ case "$1" in
     # the foler `ascii_arts`, so if, for example, there's an art called
     # `bird 4 7`in the `ascii_arts/lolcat/`, the correct way to call it should
     # be `nincat "lolcat/bird 4 7"`.
-    [ "$2" ] && [ -f "$path_script/$2" ] && selected="$path_script/$2" || {
+    [ "$2" ] && [ -f "$path_script/ascii_arts/$2" ] && selected="$path_script/ascii_arts/$2" || {
       echo "nincat: specify the secondpath of your art, if you don't know" \
            "then run nincat again with the following argument 'list'."; exit 1
     }
@@ -114,7 +120,7 @@ case "$1" in
   # NOTE 3.3
   # This will probably the option that will be often used, this prints an ASCII
   # art randomly that fits in your terminal.
-  random | r)
+  random | '-r')
 
     # NOTE 3.3.1
     # Pass columns of terminal to variable to be used twice here.
@@ -128,9 +134,21 @@ case "$1" in
     #    the name;
     # 3. 'shuf' will randomize the list
     # 4. 'head' will get the first file of the list.
-    selected="$(find "$path_script/" -type f -size +0 | \
-      awk "(\$(NF-1) < $(($(tput lines) - 1))) && (\$NF < $((columns - 2)))" | \
-      shuf | head -n1)"
+    [ -f "$path_script/nincat_list" ] && {
+      
+      selected="$path_script/ascii_arts/$(awk \
+        "(\$(NF-1) < $(($(tput lines) - 1))) && (\$NF < $(($columns - 2)))" \
+        "$path_script/nincat_list" | shuf | head -n1)"
+
+    } || {
+
+      echo "nincat: The file list was not found on the root directory.\n" \
+           "nincat will try to create it by itself. If it doesn't work, try" \
+           "running 'nincat update'."
+      "$path_script/nincat" 'update'
+      exec "$path_script/nincat" 'random'
+      
+    }
 
     # NOTE 3.3.3:
     # This block of code will only execute if an ASCII art is found, note that
@@ -143,8 +161,8 @@ case "$1" in
       # Print the name of the file, you can add $NF to print certain fields, if
       # you just want the name, remove the $(NF-2), $(NF-1) for that.
       # If you want the full path, remove the sed call in the following 2 lines
-      [ "$2" = 'see' ] || [ "$2" = 's' ] && printf "$selected\n" | \
-        sed "s*$path_script/**" | \
+      [ "$2" = 'see' ] || [ "$2" = '-s' ] && printf "$selected\n" | \
+        sed "s*$path_script/ascii_arts/**" | \
         awk '{print $(NF-2), $(NF-1), $NF}'
 
       # NOTE 3.3.3.2:
@@ -161,16 +179,31 @@ case "$1" in
 
   # NOTE 3.4:
   # Help command, show a list with what can be run by nincat and version.
-  help | h)
+  help | '-h')
 
     echo \
       "\n\033[1mnincat help with arguments in a tree list\033[0m\n" \
-      "   random <r>     : show a random ASCII art\n" \
-			"			 see <s>        : (optional) show the secondpath of the art\n" \
-      "   list <l>       : print the secondpath of all ASCII arts\n" \
-      "   view <v>       : print an ASCII art based on the secondpath\n" \
-      "			 \"\$2\"        : secondpath of the art to print\n" \
-      "		help <h>       : shows this\n"
+      "   random [-r]            : show a random ASCII art\n" \
+			"			 see [-s]            : (optional) show the secondpath of the art\n" \
+      "   list [l]               : print the secondpath of all ASCII arts\n" \
+      "   view [v]               : print an ASCII art based on the secondpath\n" \
+      "			 [path_of_file/file] : secondpath of the art to print\n" \
+      "		help [h]               : shows this\n"
+
+    exit 0
+
+  ;;
+  
+  # NOTE 3.5:
+  # Update command, it will update the list file with all the new art files.
+  update | '-u')
+  
+    find "$path_script/ascii_arts" -type f -size +0 | \
+      sed "s*$path_script/ascii_arts/**" | \
+      awk '{print $(NF-2), $(NF-1), $NF}' > "$path_script/nincat_list" \
+    && echo "nincat: Updated file with list of arts" \
+    || echo "nincat: Failed to update file with list of arts, please share" \
+            "the log of the 'find' command (if there's any) on a new issue.\n"
 
     exit 0
 
